# .readthedocs.yml

# Define the version of the configuration file format
version: 2

# Define the Python environment
python:
  version: 3.8  # Specify the Python version you need

# Define the Sphinx configuration
sphinx:
  configuration: docs/conf.py  # Path to your Sphinx configuration file

# Specify the build environment
build:
  os: ubuntu-22.04  # Choose the OS environment; options include 'ubuntu-22.04', 'ubuntu-20.04', etc.

# Define the formats to build
formats:
  - htmlzip  # Generate HTML documentation in a zip archive
  # Uncomment below if you also want to build PDF and/or EPUB formats
  # - pdf
  # - epub
