# readthedocs.yml
version: 2

# The tools used to build the documentation
build:
  tools:
    - sphinx
    - mkdocs

# The commands to run during the build process
commands:
  - pip install -r requirements.txt
  - make html
