[profile.default]
src = "src"
out = "out"
optimizer = true
# optimizer_runs = 200
# evm_version = "istanbul"
libs = ["lib"]
remappings = ['@openzeppelin/contracts=lib/openzeppelin-contracts/contracts']
solc = "0.8.24"
# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
